version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: group2-postgres-1
    environment:
      POSTGRES_USER: pg-2
      POSTGRES_PASSWORD: pg-2
      POSTGRES_DB: navigation
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pg-2 -d navigation"]
      interval: 10s
      retries: 5

  navigation-service:
    image: python:3.13-slim
    container_name: group2-navigation-service-1
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./Makefile:/Makefile
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
      - ./env/.env:/app/env/.env
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "pip install --upgrade pip && \
         pip install -r /app/requirements.txt && \
         apt update && \
         apt install make && \
         cd /app && \
         export PYTHONPATH=$$(pwd) && \
         python -m src.rpc_api.server && \
         tail -f /dev/null"

  web-backend:
    image: python:3.13-slim
    container_name: group2-web-backend-1
    depends_on:
      postgres:
        condition: service_healthy
      navigation-service:
        condition: service_started
    ports:
      - "5000:5000"
      - "5679:5678"
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
      - ./env/.env:/app/env/.env
    networks:
      - app-network
    command: >
      sh -c "pip install --upgrade pip && \
        pip install -r /app/requirements.txt && \
        cd /app && \
        export PYTHONPATH=$$(pwd) && \
        python -m src.web_backend.web_backend_controller && \
        tail -f /dev/null"

  db-init:
    image: python:3.13-slim
    container_name: db-init
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
      - ./env/.env:/app/env/.env
    networks:
      - app-network
    command: >
      sh -c "pip install --upgrade pip && \
        pip install -r /app/requirements.txt && \
        cd /app && \
        export PYTHONPATH=$$(pwd) && \
        python -m src.database.create_database"


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
