services:
  postgres:
    image: postgres:latest
    container_name: group2-postgres-1
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 10s
      retries: 5

  navigation-service:
    build:
      context: .
      dockerfile: backend/src/navigation_service/Dockerfile
    image: registry.code.fbi.h-da.de/bpse-wise2425/group2/navigation-service:latest
    container_name: group2-navigation-service-1
    ports:
      - "8000:8000"
      - "5678:5678"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  web-backend:
    build:
      context: .
      dockerfile: backend/src/web_backend/Dockerfile
    env_file:
      - backend/env/.env
    image: registry.code.fbi.h-da.de/bpse-wise2425/group2/web-backend:latest
    container_name: group2-web-backend-1
    depends_on:
      postgres:
        condition: service_healthy
      navigation-service:
        condition: service_started
    ports:
      - "4243:4243"
      - "5679:5678"
    networks:
      - app-network
    environment:
      RUNNING_IN_CONTAINER: "true"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
