version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: pg-2
      POSTGRES_PASSWORD: pg-2
      POSTGRES_DB: navigation
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    image: python:3.9-slim
    environment:
      USER: pg-2
      PASSWORD: pg-2
      HOST: postgres
      PORT: 5432
      DB_NAME: navigation
    depends_on:
      - postgres
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
    networks:
      - app-network
    command: >
      sh -c "pip install --upgrade pip && pip install -r /app/requirements.txt  && python /app/src/dijkstra_algorithm.py" 

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
