version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: group2-postgres-1
    environment:
      POSTGRES_USER: pg-2
      POSTGRES_PASSWORD: pg-2
      POSTGRES_DB: navigation
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pg-2 -d navigation"]
      interval: 10s
      retries: 5

  navigation-service:
    build:
      context: .
      dockerfile: /backend/src/navigation_service/Dockerfile
    image: registry.code.fbi.h-da.de/bpse-wise2425/group2/navigation-service:latest
    container_name: group2-navigation-service-1
    ports:
      - "8000:8000"
      - "5678:5678"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  web-backend:
    build:
      context: .
      dockerfile: /backend/src/web_backend/Dockerfile
    image: registry.code.fbi.h-da.de/bpse-wise2425/group2/web-backend:latest
    container_name: group2-web-backend-1
    depends_on:
      postgres:
        condition: service_healthy
      navigation-service:
        condition: service_started
    ports:
      - "4243:4243"
      - "5679:5678"
    networks:
      - app-network

  db-init:
    build:
      context: .
      dockerfile: /backend/src/database/Dockerfile
    image: registry.code.fbi.h-da.de/bpse-wise2425/group2/db-init:latest
    container_name: db-init
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
