version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: group2-postgres-1
    environment:
      POSTGRES_USER: pg-2
      POSTGRES_PASSWORD: pg-2
      POSTGRES_DB: navigation
    ports:
      - "5433:5432"
      - "5678:5678"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  navigation-service:
    image: python:3.13-slim
    container_name: group2-navigation-service-1
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./Makefile:/Makefile
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
    networks:
      - app-network
    command: >
      sh -c "pip install --upgrade pip && \
         pip install -r /app/requirements.txt && \
         apt update && \
         apt install make && \
         cd /app && \
         export PYTHONPATH=$$(pwd) && \
         python -m src.rpc_api.server && \
         tail -f /dev/null"

  web-backend:
    image: python:3.13-slim
    container_name: group2-web-backend-1
    depends_on:
      - postgres
      - navigation-service
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
    networks:
      - app-network
    command: >
      sh -c "pip install --upgrade pip && \
        pip install -r /app/requirements.txt && \
        cd /app && \
        export PYTHONPATH=$$(pwd) && \
        python -m src.web_backend.web_backend_controller && \
        tail -f /dev/null"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
