services:
  web-frontend:
    image: registry.code.fbi.h-da.de/bpse-wise2425/group2/web-frontend:latest
    container_name: group2-web-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4242:80"
    networks:
      - app-network

  navigation-service:
    image: registry.code.fbi.h-da.de/bpse-wise2425/group2/navigation-service:latest
    container_name: group2-navigation-service
    build:
      context: .
      dockerfile: backend/src/navigation_service/Dockerfile
    ports:
      - "8000:8000"
      - "5678:5678"
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}

  web-backend:
    image: registry.code.fbi.h-da.de/bpse-wise2425/group2/web-backend:latest
    container_name: group2-web-backend
    build:
      context: .
      dockerfile: backend/src/web_backend/Dockerfile
    depends_on:
      navigation-service:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - "4243:4243"
      - "5679:5678"
    networks:
      - app-network
    environment:
      FLASK_ENV: "production"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}

  redis:
    image: redis:latest
    container_name: group2-redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5

networks:
  app-network:
    driver: bridge
